#
# Makefile for the input misc STM acc ais2dw12 driver
#
stm_input_ais2dw12-core-y += stm_input_ais2dw12_core.o
obj-$(CONFIG_INPUT_AIS2DW12) += stm_input_ais2dw12-core.o
obj-$(CONFIG_INPUT_AIS2DW12_I2C) += stm_input_ais2dw12_i2c.o
obj-$(CONFIG_INPUT_AIS2DW12_SPI) += stm_input_ais2dw12_spi.o
