#
# Makefile for the input misc STM acc ais2ih driver
#
stm_input_ais2ih-core-y += stm_input_ais2ih_core.o
obj-$(CONFIG_INPUT_AIS2IH) += stm_input_ais2ih-core.o
obj-$(CONFIG_INPUT_AIS2IH_I2C) += stm_input_ais2ih_i2c.o
obj-$(CONFIG_INPUT_AIS2IH_SPI) += stm_input_ais2ih_spi.o
